// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: public_id.proto

package public_ids

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// represents a signed public identifier.
// signature is hmac.New(sha256.New, keystore.GetKey(key_id)).Sum(prefix + public_id)
// prefix is sent out of band
type SignedPublicID struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	KeyId     uint32                 `protobuf:"varint,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// NOTE: not optimized for size but robustness, prefix is in the public id and the proto
	Prefix        string `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPublicID) Reset() {
	*x = SignedPublicID{}
	mi := &file_public_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPublicID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPublicID) ProtoMessage() {}

func (x *SignedPublicID) ProtoReflect() protoreflect.Message {
	mi := &file_public_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPublicID.ProtoReflect.Descriptor instead.
func (*SignedPublicID) Descriptor() ([]byte, []int) {
	return file_public_id_proto_rawDescGZIP(), []int{0}
}

func (x *SignedPublicID) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SignedPublicID) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPublicID) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *SignedPublicID) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

var File_public_id_proto protoreflect.FileDescriptor

const file_public_id_proto_rawDesc = "" +
	"\n" +
	"\x0fpublic_id.proto\x12\n" +
	"public_ids\"m\n" +
	"\x0eSignedPublicID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\rR\x05keyId\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefixB1Z/github.com/minhajuddin/public_ids/pb;public_idsb\x06proto3"

var (
	file_public_id_proto_rawDescOnce sync.Once
	file_public_id_proto_rawDescData []byte
)

func file_public_id_proto_rawDescGZIP() []byte {
	file_public_id_proto_rawDescOnce.Do(func() {
		file_public_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_id_proto_rawDesc), len(file_public_id_proto_rawDesc)))
	})
	return file_public_id_proto_rawDescData
}

var file_public_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_public_id_proto_goTypes = []any{
	(*SignedPublicID)(nil), // 0: public_ids.SignedPublicID
}
var file_public_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_id_proto_init() }
func file_public_id_proto_init() {
	if File_public_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_id_proto_rawDesc), len(file_public_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_id_proto_goTypes,
		DependencyIndexes: file_public_id_proto_depIdxs,
		MessageInfos:      file_public_id_proto_msgTypes,
	}.Build()
	File_public_id_proto = out.File
	file_public_id_proto_goTypes = nil
	file_public_id_proto_depIdxs = nil
}
